-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKC/NKrQ9W5xwvLgsc1AH0TOKm8twFyspWWuc9UW12LGgCgYIKoZIzj0DAQehRANCAAQ5AGevTn4mgzabZ4iBCmImzPwmW8eOoLiEMbzMrADxzQ5fRQq4ukbwEPhVGT9dNBxcdX/Y6R4HrgnqQpDLhdCj
-----END PRIVATE KEY-----